apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app: url_shortenning
    role: store
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: url_shortenning
        role: store
      name: redis
    spec:
      containers:
      - image: redis:4.0.6
        imagePullPolicy: IfNotPresent
        name: redis

        resources:
          requests:
            memory: 64M
            cpu: 0.1
          limits:
            memory: 128M
            cpu: 0.5

        ports:
          - containerPort: 6379

        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 60

        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 60

      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: url_shortenning
    role: store
spec:
  ports:
    - port: 6379
  selector:
    app: url_shortenning
    role: store
