apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    app: url_shortenning
    role: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: url_shortenning
        role: frontend
      name: web
    spec:
      containers:
      - image: miry/url-shortening-cr
        imagePullPolicy: Always
        name: web

        resources:
          requests:
            memory: 64M
            cpu: 0.1
          limits:
            memory: 512M
            cpu: 0.5

        env:
        - name: BASENAME
          value: http://192.168.99.103:30001
        - name: REDIS_URL
          value: redis://redis:6379/1

        ports:
          - containerPort: 3000

        livenessProbe:
          httpGet:
            path: /version
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 60

        readinessProbe:
          httpGet:
            path: /version
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 60

      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---

apiVersion: v1
kind: Service
metadata:
  name: url-shortenning
  labels:
    app: url_shortenning
    role: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30001
  selector:
    app: url_shortenning
    role: frontend
